FROM gkiar/fuzzy:ubuntu14.04-libmath

RUN apt-get update && apt install -y curl libxt6 tcsh libxft2 libxp6 libxpm4 libxmu6

RUN (cd && curl -O https://afni.nimh.nih.gov/pub/dist/bin/linux_ubuntu_16_64/@update.afni.binaries &&\
    tcsh @update.afni.binaries -package linux_openmp_64 -do_extras)

ENV PATH $PATH:/root/abin