FROM ubuntu:14.04
# This Dockerfile is taken from https://github.com/verificarlo/verificarlo and
# modified slightly to decrease the image size

# Retrieve dependencies
RUN apt-get -y update &&\
    apt-get -y install --no-install-recommends bash ca-certificates make \
                                               libmpfr-dev clang-3.5 llvm-3.5 \
                                               llvm-3.5-dev dragonegg-4.7 gcc-4.7 \
                                               g++-4.7 gfortran-4.7 libgfortran-4.7-dev \
                                               autoconf automake libedit-dev libtool \
                                               libz-dev binutils git &&\
    rm -rf /var/lib/apt/lists/

ENV LIBRARY_PATH /usr/lib/gcc/x86_64-linux-gnu/4.7:/usr/lib/llvm-3.5/lib:$LIBRARY_PATH

# Download and configure verificarlo from git master
RUN mkdir -p /opt/build/ &&\
    git clone https://github.com/verificarlo/verificarlo /opt/build/verificarlo/ &&\
    cd /opt/build/verificarlo/ &&\
    ./autogen.sh &&\
    ./configure --with-llvm=/usr/lib/llvm-3.5/bin/ \
                --with-dragonegg=/usr/lib/gcc/x86_64-linux-gnu/4.7/plugin/dragonegg.so \
                CC=gcc-4.7 \
                CXX=g++-4.7

# Build and test verificarlo
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH
ENV PATH /usr/local/bin:$PATH
ENV PYTHONPATH /usr/local/lib/python3.4/site-packages/:$PYTHONPATH

RUN cd /opt/build/verificarlo &&\
    make &&\
    make install &&\
    make installcheck