FROM ubuntu:18.04

# This Dockerfile is adapted from https://github.com/verificarlo/verificarlo
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update &&\
    apt install -y autoconf\
                   automake\
                   bash ca-certificates\
                   binutils\
                   clang-4.0\
                   gcc\
                   git\
                   libedit-dev\
                   libmpfr-dev\
                   libtool\
                   libz-dev\
                   llvm-4.0\
                   llvm-4.0-dev\
                   make

ENV LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/8:/usr/lib/llvm-4.0/lib:$LIBRARY_PATH

RUN git clone https://github.com/verificarlo/verificarlo.git && \
    cd verificarlo &&\ 
    ./autogen.sh &&\
    ./configure --with-llvm=/usr/lib/llvm-4.0/bin/ CC=gcc-7 CXX=g++-7 --without-dragonegg &&\
    make && make install

