FROM ubuntu:18.04

# This Dockerfile is adapted from https://github.com/verificarlo/verificarlo
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update &&\
    apt install -y autoconf\
                   automake\
                   bash ca-certificates\
                   binutils\
                   clang-4.0\
                   gcc-4.8\
                   g++-4.8\
                   git\
                   libedit-dev\
                   libmpfr-dev\
                   libtool\
                   libz-dev\
                   llvm-4.0\
                   llvm-4.0-dev\
                   make\
                   python3\
                   python3-numpy\
                   python3-matplotlib

ENV LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.8:/usr/lib/llvm-4.0/lib:$LIBRARY_PATH

RUN git clone https://github.com/verificarlo/verificarlo.git &&\
    cd verificarlo &&\ 
    ./autogen.sh &&\
    ./configure --with-llvm=/usr/lib/llvm-4.0/bin/ CC=gcc-4.8 CXX=g++-4.8 --without-dragonegg &&\
    make &&\
    make install &&\
    make installcheck

