FROM yohanchatelain/fuzzy:python-numpy-scipy-v0.4.1

# Load backend IEEE
RUN echo "libinterflop_ieee.so" > $VFC_BACKENDS_FROM_FILE

RUN cd /opt/build &&\
  git clone https://github.com/scikit-learn/scikit-learn.git &&\
  cd scikit-learn &&\
  git checkout 0.23.2 &&\
  python3 setup.py build -j 4 install

# Remove temporary files
RUN rm -rf /opt/build/*

# Restore default behavior for verificarlo's CC
ENV CC "verificarlo-c"
RUN echo "libinterflop_mca.so -m rr" > $VFC_BACKENDS_FROM_FILE

ENTRYPOINT [ "/bin/bash"]