ARG VERIFICARLO_VERSION=v0.5.0
FROM verificarlo/verificarlo:${VERIFICARLO_VERSION}

# Setup build dependencies
RUN apt-get update -qqq &&\
    apt-get install -y --no-install-recommends -qqq \
    make build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev wget \
    curl llvm libncurses5-dev  libncursesw5-dev \
    xz-utils tk-dev wget fort77 gfortran cmake lzma-dev liblzma-dev &&\
    rm -rf /var/lib/apt/lists/ &&\
    mkdir -p /opt/build/

# Copy verificarlo's exclusion file for Python 3
COPY docker/resources/python-vfc-exclude.txt /tmp/python-vfc-exclude.txt

# Setting compilers and linkers to use verificarlo
ENV CC "verificarlo-c"
ENV CXX "verificarlo-c++"
ENV FC "verificarlo-f"

# Load backend IEEE
RUN mkdir -p /opt/ && touch /opt/vfc-backends.txt
ENV VFC_BACKENDS_FROM_FILE=/opt/vfc-backends.txt
RUN echo "libinterflop_ieee.so" > $VFC_BACKENDS_FROM_FILE

# Create instrumented shared mathematical library
COPY docker/resources/libmath/ /opt/mca-libmath/
RUN cd /opt/mca-libmath/ &&\
    make &&\
    make test


# Build BLAS and LAPACK from the following URL's instructions:
#  http://ab-initio.mit.edu/wiki/index.php/Template:Installing_BLAS_and_LAPACK
RUN cd /opt/build/ &&\
    wget http://www.netlib.org/lapack/lapack-3.9.0.tgz &&\
    gunzip lapack-3.9.0.tgz &&\
    tar xf lapack-3.9.0.tar &&\
    cd /opt/build/lapack-3.9.0/ &&\
    cp make.inc.example make.inc &&\
    sed -i 's/= gcc/= verificarlo-c/g' make.inc &&\
    sed -i 's/= gfortran/= verificarlo-f/g' make.inc &&\
    sed -i 's/TIMER    = INT_ETIME/#TIMER    = INT_ETIME/g' make.inc &&\
    sed -i 's/# TIMER = NONE/TIMER = NONE/g' make.inc &&\
    mkdir build &&\
    cd /opt/build/lapack-3.9.0/build &&\
    cmake FC=verificarlo-f -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_C_COMPILER=verificarlo-c -DCMAKE_Fortran_COMPILER=verificarlo-f \
    -DCBLAS=ON -DBUILD_SHARED_LIBS=ON  .. &&\
    make &&\
    make install

# Remove temporary files
RUN rm -rf /opt/build/*

# Restore default behavior for verificarlo's CC
ENV CC "verificarlo-c"
ENV VFC_BACKENDS_SILENT_LOAD="True"
RUN echo "libinterflop_mca.so -m rr" > $VFC_BACKENDS_FROM_FILE

# Preloading the instrumented shared library
ENV LD_PRELOAD="/opt/mca-libmath/libmath.so:/usr/local/lib/libblas.so:/usr/local/lib/libcblas.so"

# Set bash shell as entrypoint
ENTRYPOINT [ "/bin/bash"]
