ARG VERIFICARLO_VERSION=v0.6.0
FROM verificarlo/fuzzy:${VERIFICARLO_VERSION}-lapack-python3.8.5-numpy-scipy

# Load backend IEEE
RUN echo "libinterflop_ieee.so" > $VFC_BACKENDS_FROM_FILE

RUN cd /opt/build &&\
  git clone https://github.com/scikit-learn/scikit-learn.git &&\
  cd scikit-learn &&\
  git checkout 1.0.2 &&\
  python3 setup.py build -j 4 install

# Remove temporary files
RUN rm -rf /opt/build/*

# Restore default behavior for verificarlo's CC
ENV CC "verificarlo-c"
RUN echo "libinterflop_mca.so -m rr" > $VFC_BACKENDS_FROM_FILE

ENTRYPOINT [ "/bin/bash"]
