ARG VERIFICARLO_VERSION=v0.6.0
FROM verificarlo/fuzzy:${VERIFICARLO_VERSION}-lapack-python3.8.5-numpy

# Load backend IEEE
RUN echo "libinterflop_ieee.so" > $VFC_BACKENDS_FROM_FILE

RUN pip3 install joblib pythran
RUN cp /usr/local/bin/verificarlo-f /usr/bin/gfortran

RUN ln -sf $(which verificarlo) $(which x86_64-linux-gnu-gcc)

RUN cd /opt/build/ &&\
  wget https://github.com/scipy/scipy/releases/download/v1.7.3/scipy-1.7.3.tar.gz &&\
  tar xvf scipy-1.7.3.tar.gz &&\
  cd scipy-1.7.3 &&\
  CC="verificarlo-c" FC="verificarlo-f" CXX="verificarlo-c++" CFGLAGS="--conservative -Wunused-command-line-argument" \
  python3 setup.py build -j $(nproc) --disable-optimization install


# Remove temporary files
RUN rm -rf /opt/build/*

# Restore default behavior for verificarlo's CC
ENV CC "verificarlo-c"
RUN echo "libinterflop_mca.so -m rr" > $VFC_BACKENDS_FROM_FILE

ENTRYPOINT [ "/bin/bash"]
