ARG VERIFICARLO_VERSION=v0.5.0
FROM yohanchatelain/fuzzy:${VERIFICARLO_VERSION}-lapack-python3.8.5-numpy

# Load backend IEEE
RUN echo "libinterflop_ieee.so" > $VFC_BACKENDS_FROM_FILE

# Setting compilers and linkers to use verificarlo
ENV CC "verificarlo-c --conservative"
ENV CXX "verificarlo-c++ --conservative"
ENV FC "verificarlo-f --conservative"

RUN pip3 install joblib
RUN cp /usr/local/bin/verificarlo-f /usr/bin/gfortran
RUN cd /opt/build/ &&\
  git clone https://github.com/scipy/scipy.git &&\
  cd /opt/build/scipy &&\
  git checkout v1.5.4 &&\
  OPT="--conservative" FOPT="--conservative" NPY_NUM_BUILD_JOBS=4 \
  python3 setup.py config --compiler=verificarlo --fcompiler=verificarlof build_clib \
  --compiler=verificarlo --fcompiler=verificarlof build_ext \
  --compiler=verificarlo --fcompiler=verificarlof build -j 4 install

# Remove temporary files
RUN rm -rf /opt/build/*

# Check that no AVX2/AVX512 instructions are emitted
RUN if [[ $( objdump -d /usr/local/lib/python3.8/site-packages/scipy-1.5.4-py3.8-linux-x86_64.egg/scipy/linalg/cython_blas.cpython-38-x86_64-linux-gnu.so | grep "%ymm\|%zmm" | wc -l ) != 0 ]] ; then exit 1 ; fi


# Restore default behavior for verificarlo's CC
ENV CC "verificarlo-c"
# Restore default MCA mode
RUN echo "libinterflop_mca.so -m rr" > $VFC_BACKENDS_FROM_FILE

ENTRYPOINT [ "/bin/bash"]
