ARG VERIFICARLO_VERSION=v0.5.0
FROM verificarlo/fuzzy:${VERIFICARLO_VERSION}-lapack

# Setting compilers and linkers to use verificarlo
ENV CC "verificarlo-c --conservative"
ENV CXX "verificarlo-c++ --conservative"
ENV FC "verificarlo-f --conservative"

# Use IEEE mode for compiling with verificarlo
RUN echo "libinterflop_ieee.so" > $VFC_BACKENDS_FROM_FILE

# Remove any existing python packages
RUN apt -y -qqq remove python3

## Build Python 3.8.5 from source and the associated pip
RUN cd /opt/build/ && \
    wget https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tgz && \
    tar xvf Python-3.8.5.tgz && \
    cd Python-3.8.5 && \
    CFLAGS="--exclude-file=/tmp/python-vfc-exclude.txt --conservative -Wunused-command-line-argument" ./configure --enable-optimizations --with-ensurepip=install &&\
    make -j &&\
    make install &&\ 
    wget https://bootstrap.pypa.io/get-pip.py &&\
    python3 get-pip.py

# Remove temporary files
RUN rm -rf /opt/build/*

# Check that no AVX2/AVX512 instructions are emitted
RUN if [ $( objdump -d $(which python3) | grep "%ymm\|%zmm" | wc -l ) != 0 ] ; then exit 1 ; fi

# Restore default behavior for verificarlo's CC
ENV CC "verificarlo-c"
# Restore default MCA mode
RUN echo "libinterflop_mca.so -m rr" > $VFC_BACKENDS_FROM_FILE

# Set entrypoint
ENTRYPOINT [ "/bin/bash"]
