ARG ORG=verificarlo
ARG VERIFICARLO_VERSION=v2.0.0
FROM ${ORG}/fuzzy:${VERIFICARLO_VERSION}-numpy

ARG SCIPY_VERSION=1.10.1

# Copy sanity check for SciPy
COPY docker/resources/scipy-vfc-exclude.txt /tmp/scipy-vfc-exclude.txt
COPY docker/resources/scipy-sanity-check.py /tmp/scipy-sanity-check.py

# Load backend IEEE
RUN echo "libinterflop_ieee.so" > $VFC_BACKENDS_FROM_FILE && \
  # Install patchelf
  apt-get update && apt-get install -y patchelf && \
  # Install SciPy dependencies
  pip3 install joblib pythran pybind11 cython==0.29.32 && \
  # Remove debug flag which makes compilation crash
  sed -i "498s/.*/    llvm_options = llvm_options.replace(\"-g\",'') if \"-g\" in llvm_options else llvm_options/" $(which verificarlo) && \
  cd /opt/build/ && \
  wget https://github.com/scipy/scipy/releases/download/v${SCIPY_VERSION}/scipy-${SCIPY_VERSION}.tar.gz &&\
  tar xvmf scipy-${SCIPY_VERSION}.tar.gz &&\
  cd scipy-${SCIPY_VERSION} &&\
  CC="verificarlo-c" FC="verificarlo-f" F77="verificarlo-f" F90="verificarlo-f" CXX="verificarlo-c++" \
  PY_LDFLAGS="--inst-fma -shared ${PY_LDFLAGS}" \
  PY_CORE_LDFLAGS="--inst-fma -shared ${PY_CORE_LDFLAGS}" \
  LDSHARED='verificarlo-c' \
  CFLAGS="--exclude-file=/tmp/scipy-vfc-exclude.txt --inst-fma" \
  CXXFLAGS="--exclude-file=/tmp/scipy-vfc-exclude.txt --inst-fma" \
  FCFLAGS="--exclude-file=/tmp/scipy-vfc-exclude.txt --inst-fma" \
  LDFLAGS="-shared -lflang -lpgmath" \
  NPY_NUM_BUILD_JOBS=$(nproc) \
  python3 setup.py install

# Restore original verificarlo
RUN sed -i "498s/    llvm_options = llvm_options.replace(\"-g\",'') if \"-g\" in llvm_options else llvm_options//" $(which verificarlo) && \
  # Set default MCA mode
  echo "libinterflop_mca.so -m rr" > $VFC_BACKENDS_FROM_FILE && \
  # Sanity check
  cd && python3 /tmp/scipy-sanity-check.py && \
  rm -rf /opt/build/*

# Restore default behavior for verificarlo's CC
ENV CC "verificarlo-c"
# Needed for scipy to find the shared libraries (libpgmath)
ENV LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/:${LD_LIBRARY_PATH}

ENTRYPOINT [ "/bin/bash"]