FROM verificarlo/verificarlo:latest

RUN apt-get update -qqq &&\
    apt-get install -y -qqq make build-essential libssl-dev zlib1g-dev \
                            libbz2-dev libreadline-dev libsqlite3-dev wget \
                            curl llvm libncurses5-dev  libncursesw5-dev \
                            xz-utils tk-dev wget &&\
    rm -rf /var/lib/apt/lists/

# Copy verificarlo's exclusion file for Python 3
COPY python-vfc-exclude.txt /tmp/python-vfc-exclude.txt

# When compiling C, use exclusion file
ENV CC "verificarlo --exclude-file /tmp/python-vfc-exclude.txt"
ENV FC "verificarlo"
ENV LD "verificarlo"
ENV LDSHARED "verificarlo -shared"

# Replace IEEE with MCA and MPFR with QUAD after build
ENV VERIFICARLO_MCAMODE "IEEE"
ENV VERIFICARLO_PRECISION "53"
ENV VERIFICARLO_BACKEND "MPFR"

RUN mkdir -p /opt/build/ && \
    cd /opt/build/ && \
    wget https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tgz && \
    tar xvf Python-3.6.5.tgz && \
    cd Python-3.6.5 && ./configure --enable-optimizations --with-ensurepip=install

RUN cd /opt/build/Python-3.6.5 && make

# Restore default behavior for verificarlo's CC
ENV CC "verificarlo"
ENV VERIFICARLO_MCAMODE "MCA"
ENV VERIFICARLO_BACKEND "QUAD"

ENTRYPOINT [ "/bin/bash"]
