FROM verificarlo/verificarlo:latest

COPY verificarlo.patch /tmp/verificarlo.patch
COPY vfcwrapper.patch /tmp/vfcwrapper.patch


RUN apt-get update -qqq &&\
  apt-get install -y -qqq make build-essential libssl-dev zlib1g-dev \
  libbz2-dev libreadline-dev libsqlite3-dev wget \
  curl llvm libncurses5-dev  libncursesw5-dev \
  xz-utils tk-dev wget fort77 gfortran cmake liblzma-dev &&\
  rm -rf /var/lib/apt/lists/ &&\
  mkdir -p /opt/build/

RUN patch $(which verificarlo) /tmp/verificarlo.patch
RUN patch /usr/local/include/vfcwrapper.c /tmp/vfcwrapper.patch

# Copy verificarlo's exclusion file for Python3
COPY python-vfc-exclude.txt /tmp/python-vfc-exclude.txt
# Copy verificarlo's exclusion file for Numpy
COPY numpy-vfc-exclude.txt /tmp/numpy-vfc-exclude.txt

# Setting compilers and linkers to use verificarlo
ENV CC "verificarlo-c"
ENV CXX "verificarlo-c++"
ENV FC "verificarlo-f"

# Load backend IEEE
RUN touch /tmp/vfc-backends.txt
ENV VFC_BACKENDS_FROM_FILE=/tmp/vfc-backends.txt
RUN echo "libinterflop_ieee.so" > $VFC_BACKENDS_FROM_FILE

## Build Python 3.6.5 from source and the associated pip
RUN cd /opt/build/ && \
  git clone https://github.com/python/cpython.git &&\
  cd cpython &&\
  git checkout v3.8.5 &&\
  CFLAGS="--exclude-file=/tmp/python-vfc-exclude.txt" ./configure --enable-optimizations --with-ensurepip=install || cat config.log &&\
  make -j &&\
  make install &&\ 
  wget https://bootstrap.pypa.io/get-pip.py &&\
  python3 get-pip.py

# Build BLAS and LAPACK from the following URL's instructions:
#  http://ab-initio.mit.edu/wiki/index.php/Template:Installing_BLAS_and_LAPACK
RUN cd /opt/build/ &&\
  wget http://www.netlib.org/lapack/lapack-3.9.0.tgz &&\
  gunzip lapack-3.9.0.tgz &&\
  tar xf lapack-3.9.0.tar &&\
  cd /opt/build/lapack-3.9.0/ &&\
  cp make.inc.example make.inc &&\
  sed -i 's/= gcc/= verificarlo-c/g' make.inc &&\
  sed -i 's/= gfortran/= verificarlo-f/g' make.inc &&\
  sed -i 's/TIMER    = INT_ETIME/#TIMER    = INT_ETIME/g' make.inc &&\
  sed -i 's/# TIMER = NONE/TIMER = NONE/g' make.inc &&\
  mkdir build &&\
  cd /opt/build/lapack-3.9.0/build &&\
  cmake FC=verificarlo-f -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_C_COMPILER=verificarlo-c -DCMAKE_Fortran_COMPILER=verificarlo-f \
  -DCBLAS=ON -DBUILD_SHARED_LIBS=ON  .. &&\
  make &&\
  make install

COPY numpy-verificarlo.patch /tmp/numpy-verificarlo.patch

RUN  git config --global user.email "fake@mail.com" &&\
  git config --global user.name "Anonymous Patcher" 


# Build numpy from sources and link with the local BLAS and LAPACK
# CC=verificarlo-c FC=verificarlo-f CFLAGS="--verbose" LAPACK=~/local/lib/liblapack.so BLAS=~/local/lib/libblas.so \
#   NPY_BLAS_ORDER=BLAS NPY_LAPACK_ORDER=LAPACK python3 setup.py build  -j 4
RUN pip3.8 install cython
RUN cd /opt/build &&\
  git clone https://github.com/numpy/numpy.git &&\
  cd /opt/build/numpy &&\
  git checkout v1.19.1 &&\
  git am /tmp/numpy-verificarlo.patch &&\
  CFLAGS="--exclude-file=/tmp/numpy-vfc-exclude.txt -Wunused-command-line-argument" \
  NPY_BLAS_ORDER=BLAS NPY_LAPACK_ORDER=LAPACK \
  python3 setup.py config --compiler=verificarlo --fcompiler=verificarlof build_clib \
  --compiler=verificarlo --fcompiler=verificarlof build_ext \
  --compiler=verificarlo --fcompiler=verificarlof build -j 4 install

RUN cp /usr/local/bin/verificarlo-f /usr/bin/gfortran
RUN cd /opt/build/ &&\
  git clone https://github.com/scipy/scipy.git &&\
  cd /opt/build/scipy &&\
  git checkout v1.5.4 &&\
  CFLAGS="--disable-debug-flag" FFLAGS="--disable-debug-flag" NPY_NUM_BUILD_JOBS=4 \
  python3 setup.py config --compiler=verificarlo --fcompiler=verificarlof build_clib \
  --compiler=verificarlo --fcompiler=verificarlof build_ext \
  --compiler=verificarlo --fcompiler=verificarlof build -j 4 install

RUN pip3 install joblib

# Restore default behavior for verificarlo's CC
ENV CC "verificarlo-c"
RUN echo "libinterflop_mca.so -m rr" > $VFC_BACKENDS_FROM_FILE

ENTRYPOINT [ "/bin/bash"]