FROM verificarlo/verificarlo:latest

RUN apt-get update -qqq &&\
    apt-get install -y -qqq make build-essential libssl-dev zlib1g-dev \
                            libbz2-dev libreadline-dev libsqlite3-dev wget \
                            curl llvm libncurses5-dev  libncursesw5-dev \
                            xz-utils tk-dev wget fort77 gfortran cmake &&\
    rm -rf /var/lib/apt/lists/ &&\
    mkdir -p /opt/build/

# Ensure Verificarlo is behaving itself
ENV CC "gcc"
ENV CXX "gcc"
ENV FC "gfortran"
ENV LD "gcc"
ENV LDSHARED "gcc -shared"
ENV VERIFICARLO_MCAMODE "IEEE"
ENV VERIFICARLO_PRECISION "53"
ENV VERIFICARLO_BACKEND "MPFR"

# Build BLAS and LAPACK from the following URL's instructions:
#  http://ab-initio.mit.edu/wiki/index.php/Template:Installing_BLAS_and_LAPACK
RUN cd /opt/build/ &&\
    wget http://www.netlib.org/lapack/lapack-3.5.0.tgz &&\
    gunzip lapack-3.5.0.tgz &&\
    tar xf lapack-3.5.0.tar &&\
    cd /opt/build/lapack-3.5.0/ &&\
    cp make.inc.example make.inc &&\
    cd /opt/build/lapack-3.5.0/BLAS/SRC/ &&\
    make &&\
    cd /opt/build/lapack-3.5.0/ &&\
    cmake . && make &&\
    cp lib/* /usr/local/lib/

## Get Python 3.6.5 and the associated pip
RUN apt-get update -qqq && \
    apt-get install -y software-properties-common &&\
    add-apt-repository ppa:deadsnakes/ppa &&\
    apt-get update -qqq && \
    apt-get install -y python3.6 &&\
    curl https://bootstrap.pypa.io/get-pip.py | python3.6

ENTRYPOINT [ "/bin/bash"]
