FROM gkiar/fuzzy:ubuntu14.04-base

RUN apt-get update &&\
    apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
                       libreadline-dev libsqlite3-dev wget curl libncurses5-dev \
                       libncursesw5-dev xz-utils tk-dev cmake &&\
    rm -rf /var/lib/apt/lists/ &&\
    mkdir -p /opt/build/

# Setting compilers and linkers to use verificarlo
ENV CC "verificarlo"
ENV CXX "verificarlo"
ENV FC "verificarlo"
ENV LD "verificarlo"
ENV LDSHARED "verificarlo -shared"

# Build BLAS and LAPACK from the following URL's instructions:
#  http://ab-initio.mit.edu/wiki/index.php/Template:Installing_BLAS_and_LAPACK
RUN cd /opt/build/ &&\
    wget http://www.netlib.org/lapack/lapack-3.5.0.tgz &&\
    gunzip lapack-3.5.0.tgz &&\
    tar xf lapack-3.5.0.tar &&\
    cd /opt/build/lapack-3.5.0/ &&\
    cp make.inc.example make.inc &&\
    sed -i 's/= gcc\|= gfortran/= verificarlo/g' make.inc &&\
    sed -i 's/-frecursive/-fPIC -frecursive/g' make.inc &&\
    cd /opt/build/lapack-3.5.0/BLAS/SRC/ &&\
    make &&\
    cd /opt/build/lapack-3.5.0/SRC/ &&\
    make &&\
    cd /opt/build/lapack-3.5.0/ &&\
    cp librefblas.a /usr/local/lib/libblas.a &&\
    cp liblapack.a /usr/local/lib/liblapack.a

# Restore default behavior for verificarlo's CC
ENV VFC_BACKENDS "libinterflop_mca.so -m mca"