FROM verificarlo/verificarlo:latest

# Create instrumented shared mathematical library
RUN git clone https://github.com/big-data-lab-team/MCA-libmath.git /tmp/mca-libmath/ &&\
    cd /tmp/mca-libmath/src/ &&\
    make

# Preloading the instrumented shared library
ENV LD_PRELOAD=/tmp/mca-libmath/src/libpreload.so
ENV VFC_BACKENDS="libinterflop_mca.so --mode mca" \
    VFC_BACKENDS_SILENT_LOAD="True"
