FROM gkiar/fuzzy:ubuntu14.04-base


# Compile openlibmath with verificarlo 
RUN cd /tmp/ && \
    git clone https://github.com/JuliaMath/openlibm
ADD ./cmtd_assm.files /tmp/openlibm/amd64/Make.files
RUN cd /tmp/openlibm && \
    make CC=verificarlo

# Set LS_PRELOAD variable to first load the new lib instead of libm
ENV LD_PRELOAD=/tmp/openlibm/libopenlibm.so
ENV VFC_BACKENDS="libinterflop_mca.so"
 
