FROM alpine:3.7

# Installing dependencies for Verificarlo
RUN apk update &&\
    apk add build-base mpfr-dev make llvm-dev gfortran \
            g++ automake python3 autoconf clang &&\
    mkdir -p /opt/build/ && cd /opt/build/ &&\
    wget http://llvm.org/releases/3.3/dragonegg-3.3.src.tar.gz &&\
    tar xzf dragonegg-3.3.src.tar.gz &&\
    cd dragonegg-3.3.src/

# TODO: make dragonegg install work on Alpine...
# TODO: finish install