FROM verificarlo/fuzzy:v0.4.1-libmath

ENV VFC_BACKENDS="libinterflop_ieee.so"

# Install FSL tools
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update -y 
RUN apt install -y python2 \
    wget vim \
    libopenblas-base \
    tar \
    unzip \
    bc \
    libglu1-mesa-dev \
    freeglut3-dev \
    mesa-common-dev \
    libfreetype6 \
    qt5-default \
    libosmesa-dev

RUN ln -s /usr/bin/python2.7 /usr/bin/python

ADD ./fslinstaller.py /tmp/
RUN cd /tmp/ &&\
    python fslinstaller.py 
    
# Clone HCP pipelines
RUN wget https://github.com/Washington-University/Pipelines/archive/v4.2.0.tar.gz -O pipelines.tar.gz; \
    tar zxvf /pipelines.tar.gz -C /usr/local/src/; \
    mv /usr/local/src/HCPpipelines-* /usr/local/src/pipelines; \
    rm -rf pipelines.tar.gz; \
    mkdir -p /usr/local/src/tools; \
    wget https://humanconnectome.org/storage/app/media/workbench/workbench-linux64-v1.4.2.zip -O workbench.zip; \
    unzip workbench.zip -d /usr/local/src/tools; \
    rm -rf workbench.zip;

# Link pipelines folder
RUN mkdir /usr/local/src/projects; \
    ln -s /usr/local/src/pipelines /usr/local/src/HCPpipelines; \
    ln -s /usr/local/src/pipelines /usr/local/src/projects/Pipelines;

# Install Freesurfer 6.0.0 HCP centos6 build
RUN apt install -y \
    libgomp1 \
    tcsh \
    libxmu6 \
    libglu1

# RUN wget ftp://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.1.1/freesurfer-linux-centos7_x86_64-7.1.1.tar.gz -O freesurfer-centos7-v7.1.1.tar.gz; \
RUN wget ftp://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/6.0.0/freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.0.tar.gz -O freesurfer-centos6-v6.0.0.tar.gz; \
    tar -zxvf freesurfer-centos6-v6.0.0.tar.gz -C /usr/local/src; \
    rm -rf freesurfer-centos6-v6.0.0.tar.gz; 

# Set environment variables for FSL
ENV FSLDIR=/usr/local/fsl \
    FSLOUTPUTTYPE=NIFTI_GZ \
    FSLGECUDAQ=cuda.q \
    CARET7DIR=/usr/local/src/tools/workbench

ENV PATH=${FSLDIR}/bin:${CARET7DIR}/exe_linux64:/usr/local/src/pipelines/FreeSurfer/custom:${PATH} \
    FSLTCLSH=${FSLDIR}/bin/fsltclsh \
    FSLWISH=${FSLDIR}/bin/fslwish

ENV HOME=/usr/local/src \
    PATH=${PATH}:/usr/local/src/pipelines/Examples/Scripts

# Set environment variable for FreeSurfer
ENV FS_OVERRIDE=0 \
    OS=Linux \
    FSF_OUTPUT_FORMAT=nii.gz \
    FIX_VERTEX_AREA=\
    FREESURFER_HOME=/usr/local/src/freesurfer
ENV MNI_DIR=$FREESURFER_HOME/mni 
ENV PERL5LIB=$MNI_DIR/share/perl5 \
    MNI_PERL5LIB=$MNI_DIR/share/perl5 \
    MINC_BIN_DIR=$MNI_DIR/bin \
    MINC_LIB_DIR=$MNI_DIR/lib \
    MNI_DATAPATH=$MNI_DIR/data
ENV PATH=$FREESURFER_HOME/bin:$FREESURFER_HOME/tktools:$MINC_BIN_DIR:$PATH

